#!/bin/bash

self="$0"
bindir="$(dirname "${self}")"

# cleanup
find . -name "*~" -print
find . -name "*~" -exec rm "{}" \;
clear
echo

# regenerate packages from grammar
# ( $bindir/make-parser ) 2>&1 | tee LOG-GENERATE

rm -rf X/* BUILD-* tests/core
mkdir  X
./build.tcl test --log X/X --test-include ~/opt/ActiveTcl/include
#./build.tcl test --log-mode full --test-include ~/opt/ActiveTcl/include 2>&1 | tee TL
