#!/bin/bash

g="g/doctools.slif"
v=1
a="Andreas Kupries"
base="doctools::parser::"

marpa-gen \
    -V $v -A "${a}" \
    -T cparse-critcl \
    -N ${base}c \
    $g doctools-c.tcl
echo

marpa-gen \
    -V $v -A "${a}" \
    -T tparse \
    -N ${base}tcl \
    $g doctools-tcl.tcl
echo
