[comment {-*- tcl -*- --- !doctools --- manpage}]
[comment {- - -- --- ----- -------- ------------- ---------------------}]
[section {Bugs, Ideas, Feedback}]
[vset R https://core.tcl.tk/akupries/marpatcl]

This document, and the package it describes, will undoubtedly contain
bugs and other problems.

Please report such at the
[uri [vset R] {Marpa/Tcl Tracker}].

Please also report any ideas for enhancements you may have for either
package and/or documentation.

