[vset repo.main    [uri https://core.tcl-lang.org/akupries/marpa]]
[vset repo.alias   [uri https://core.tcl.tk/akupries/marpa]]
[vset repo.chisel  [uri https://chiselapp.com/user/andreas_kupries/repository/marpa/index]]
[vset repo.github  [uri https://github.com/andreas-kupries/marpa]]
[vset tracker      [uri https://core.tcl-lang.org/akupries/marpatcl {Marpa/Tcl Tracker}]]

[vset fossil.scm  [uri http://www.fossil-scm.org {Fossil SCM}]]
[vset fossil.bin  [uri http://www.fossil-scm.org/download.html {download page}]]
[vset marpa.r2    [uri https://jeffreykegler.github.io/Marpa-web-site/ Marpa::R2]]
[vset marpa.lib   [uri http://jeffreykegler.github.io/Marpa-web-site/libmarpa.html]]
[vset marpa.doc	  [uri https://metacpan.org/pod/distribution/Marpa-R2/pod/Marpa_R2.pod {upstream documentation}]]

[vset mutf8.doc   [uri https://en.wikipedia.org/wiki/UTF-8#Modified_UTF-8 {Modified UTF-8}]]
[vset cesu8.doc   [uri https://en.wikipedia.org/wiki/UTF-8#CESU-8 {CESU-8}]]
