[comment {--- Standard header for all manpages in this module --}]
[comment {--- Project variables referencable in all documents ---}]
[vset p.name Marpa/Tcl]

[include locations.inc]
[include xreferences.inc]

[copyright {2015-present Andreas Kupries}]
[copyright {2018-present Documentation, Andreas Kupries}]

[moddesc   "[vset p.name], a binding to libmarpa"]

[keywords {document processing} {context free grammar}]
[keywords libmarpa parsing lexing earley aycock horspool]
[keywords {joop leo} {nigel horspool} {table parsing}]
[keywords regex {character classes}]
