#!/bin/bash
clear
echo
ftilde
rtilde
rm -rf X.* BUILD-marpa0 tests/core*
./build.tcl test --log X
#exit

show=0
if [ -s X.stacktrace ]
then
    echo
    echo SHOWING STACK TRACES in 3,2,1 ...
    sleep 2
    clear
    echo
    less X.stacktrace
    show=1
fi

if [ -s X.faildetails ]
then
    echo
    echo SHOWING FAILS in 3,2,1 ...
    sleep 2
    clear
    echo
    less X.faildetails
    show=1
fi

if [ $show -gt 0 ]
then
    clear
    echo
    cat X.summary
fi
