#!/bin/bash
clear
echo
ftilde
rtilde
rm -rf X.* BUILD-marpa0 tests/core*

# # Create all missing result files for new .slif test cases.
# (   cd tests/grammars
#     for i in $(find . -type f -name slif)
#     do
# 	touch $(dirname $i)/ctrace
# 	touch $(dirname $i)/ast
#     done
# )

./build.tcl test --log X
#exit

rm -rf BUILD-marpa0

show=0
if [ -s X.stacktrace ]
then
    echo
    echo SHOWING STACK TRACES in 3,2,1 ...
    sleep 2
    clear
    echo
    less X.stacktrace
    show=1
fi

if [ -s X.faildetails ]
then
    echo
    echo SHOWING FAILS in 3,2,1 ...
    sleep 2
    clear
    echo
    less X.faildetails
    show=1
fi

if [ $show -gt 0 ]
then
    clear
    echo
    cat X.summary
fi
